---
name: Build Docker images
on:
  push:
    branches:
      - "main"
  workflow_call:
    inputs:
      push:
        required: false
        type: boolean
env:
    REGISTRY: registry.digitalocean.com
    REPO_NS: zweiund40

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth DigitalOcean
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login DOCR
        run: doctl registry login --expiry-seconds 1000

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ env.REGISTRY }}/${{ env.REPO_NS }}/wine-10:latest .

      - name: Push service
        run: |
            docker push ${{ env.REGISTRY }}/${{ env.REPO_NS }}/wine-10:latest